services:
  goof:
    build: .
    environment:
      - DOCKER=${APP_ENV}
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
    depends_on:
      - goof-mongo

  goof-mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - "27017:27017"

  goof-mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
